import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Play, Square, Star, Trash2, Clock, Gamepad2 } from 'lucide-react';
import { formatPlayTime, formatLastPlayed } from '../utils/format';
export const GameCard = ({ game, isRunning, onLaunch, onTerminate, onToggleFavorite, onRequestRemove }) => {
    return (_jsxs("div", { className: "group relative flex flex-col bg-surface-container-low rounded-xl border border-outline-variant/60 hover:border-primary-container/80 transition-all duration-200 overflow-hidden shadow-lg hover:shadow-amber-glow/20", children: [_jsxs("div", { className: "relative aspect-[3/4] w-full bg-surface-container overflow-hidden", children: [game.coverPath ? (_jsx("img", { src: game.coverPath, alt: game.name, className: "w-full h-full object-cover transition-transform duration-300 group-hover:scale-105", onError: (e) => {
                            // Hide broken image link
                            ;
                            e.target.style.display = 'none';
                        } })) : (_jsxs("div", { className: "w-full h-full flex flex-col items-center justify-center p-4 bg-gradient-to-b from-surface-variant to-surface-container-high text-on-surface-variant", children: [_jsx(Gamepad2, { className: "w-12 h-12 text-primary/40 mb-2 group-hover:scale-110 group-hover:text-primary transition-all duration-200" }), _jsx("span", { className: "font-headline font-bold text-center text-sm text-on-surface line-clamp-2 px-2", children: game.name })] })), _jsxs("div", { className: "absolute top-2.5 inset-x-2.5 flex items-center justify-between z-10", children: [isRunning ? (_jsxs("span", { className: "flex items-center space-x-1.5 bg-black/80 backdrop-blur-md border border-status-running/60 text-status-running text-[10px] font-mono px-2 py-0.5 rounded-full shadow-md animate-pulse", children: [_jsx("span", { className: "w-1.5 h-1.5 rounded-full bg-status-running" }), _jsx("span", { children: "RUNNING" })] })) : (_jsx("span", { className: "bg-black/70 backdrop-blur-md text-[10px] font-mono text-on-surface-variant px-2 py-0.5 rounded border border-white/10", children: game.platform || 'PC' })), _jsxs("div", { className: "flex items-center space-x-1 opacity-0 group-hover:opacity-100 transition-opacity duration-150", children: [_jsx("button", { onClick: (e) => {
                                            e.stopPropagation();
                                            onToggleFavorite(game);
                                        }, className: `p-1.5 rounded-lg bg-black/70 backdrop-blur-md border border-white/10 hover:border-primary-container text-on-surface-variant hover:text-primary transition-colors ${game.favorite ? 'text-primary' : ''}`, title: game.favorite ? 'Favorited' : 'Favorite', children: _jsx(Star, { className: `w-3.5 h-3.5 ${game.favorite ? 'fill-primary' : ''}` }) }), _jsx("button", { onClick: (e) => {
                                            e.stopPropagation();
                                            onRequestRemove(game);
                                        }, className: "p-1.5 rounded-lg bg-black/70 backdrop-blur-md border border-white/10 hover:border-status-error text-on-surface-variant hover:text-status-error transition-colors", title: "Remove from Library", children: _jsx(Trash2, { className: "w-3.5 h-3.5" }) })] })] }), _jsxs("div", { className: "absolute inset-0 bg-gradient-to-t from-background via-background/40 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-200 flex flex-col justify-end p-4", children: [_jsxs("div", { className: "text-[11px] font-mono text-on-surface-variant space-y-0.5 mb-3", children: [_jsxs("div", { className: "flex items-center space-x-1.5", children: [_jsx(Clock, { className: "w-3 h-3 text-primary" }), _jsxs("span", { children: [formatPlayTime(game.playTime), " played"] })] }), _jsxs("div", { children: ["Last: ", formatLastPlayed(game.lastPlayed)] })] }), isRunning ? (_jsxs("button", { onClick: () => onTerminate(game.id), className: "w-full bg-status-running hover:bg-red-600 text-black hover:text-white font-headline text-xs font-bold py-2 rounded-lg flex items-center justify-center space-x-1.5 transition-all active:scale-95 shadow-md", children: [_jsx(Square, { className: "w-3.5 h-3.5 fill-current" }), _jsx("span", { children: "STOP" })] })) : (_jsxs("button", { onClick: () => onLaunch(game.id), className: "w-full bg-primary-container hover:bg-primary text-black font-headline text-xs font-bold py-2 rounded-lg flex items-center justify-center space-x-1.5 transition-all active:scale-95 shadow-amber-glow", children: [_jsx(Play, { className: "w-3.5 h-3.5 fill-black stroke-none" }), _jsx("span", { children: "PLAY" })] }))] })] }), _jsxs("div", { className: "p-3 bg-surface-container-low border-t border-outline-variant/40 flex items-center justify-between", children: [_jsxs("div", { className: "min-w-0 pr-2", children: [_jsx("h3", { className: "font-headline font-semibold text-xs text-on-surface truncate", children: game.name }), _jsxs("p", { className: "text-[10px] font-mono text-on-surface-variant truncate mt-0.5", children: [formatPlayTime(game.playTime), " \u2022 ", formatLastPlayed(game.lastPlayed)] })] }), _jsx("button", { onClick: () => (isRunning ? onTerminate(game.id) : onLaunch(game.id)), className: `shrink-0 p-1.5 rounded-lg border transition-all active:scale-95 ${isRunning
                            ? 'bg-status-running/20 border-status-running text-status-running hover:bg-red-500/20 hover:border-red-500 hover:text-red-400'
                            : 'bg-surface-container border-outline-variant hover:border-primary-container text-primary hover:bg-primary-container hover:text-black'}`, title: isRunning ? 'Stop' : 'Play', children: isRunning ? (_jsx(Square, { className: "w-3.5 h-3.5 fill-current" })) : (_jsx(Play, { className: "w-3.5 h-3.5 fill-current" })) })] })] }));
};
