import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Home, Gamepad2, Settings, PlusCircle, HardDrive, Terminal } from 'lucide-react';
export const Sidebar = ({ currentTab, onSelectTab, onOpenAddModal, telemetry }) => {
    return (_jsx("aside", { className: "w-60 h-screen fixed left-0 top-0 flex flex-col justify-between shrink-0 select-none bg-surface-container-low border-r border-primary-container/20 z-30", children: _jsxs("div", { className: "flex flex-col h-full py-4 px-3 justify-between", children: [_jsxs("div", { className: "flex flex-col", children: [_jsxs("div", { className: "flex items-center space-x-3 px-3 py-2 mb-6", children: [_jsx("div", { className: "w-9 h-9 rounded-lg bg-surface-container-high border border-primary-container/50 flex items-center justify-center text-primary-container shadow-amber-glow", children: _jsx(Terminal, { className: "w-5 h-5 text-primary-container stroke-[2.5]" }) }), _jsxs("div", { children: [_jsxs("div", { className: "flex items-center space-x-2", children: [_jsx("span", { className: "font-headline text-2xl font-extrabold tracking-tight text-primary leading-none", children: "X1" }), _jsx("span", { className: "font-mono text-[10px] font-semibold bg-surface-container-high text-primary px-1.5 py-0.5 rounded border border-primary-container/30", children: "V0.1.0" })] }), _jsx("p", { className: "font-mono text-[10px] text-on-surface-variant/70 tracking-widest uppercase mt-0.5", children: "GAME ENGINE CORE" })] })] }), _jsxs("nav", { className: "space-y-1.5", children: [_jsxs("button", { onClick: () => onSelectTab('home'), className: `w-full flex items-center space-x-3 font-medium text-sm pl-3.5 py-2.5 rounded-lg transition-all duration-150 active:scale-[0.98] ${currentTab === 'home'
                                        ? 'bg-surface-container-high text-primary border-l-2 border-primary-container font-semibold shadow-[inset_4px_0_12px_rgba(245,158,11,0.15)]'
                                        : 'text-on-surface-variant hover:bg-surface-container-high hover:text-primary'}`, children: [_jsx(Home, { className: `w-4 h-4 ${currentTab === 'home' ? 'text-primary' : ''}` }), _jsx("span", { children: "Home" })] }), _jsxs("button", { onClick: () => onSelectTab('library'), className: `w-full flex items-center space-x-3 font-medium text-sm pl-3.5 py-2.5 rounded-lg transition-all duration-150 active:scale-[0.98] ${currentTab === 'library'
                                        ? 'bg-surface-container-high text-primary border-l-2 border-primary-container font-semibold shadow-[inset_4px_0_12px_rgba(245,158,11,0.15)]'
                                        : 'text-on-surface-variant hover:bg-surface-container-high hover:text-primary'}`, children: [_jsx(Gamepad2, { className: `w-4 h-4 ${currentTab === 'library' ? 'text-primary' : ''}` }), _jsx("span", { children: "Library" })] }), _jsxs("button", { onClick: () => onSelectTab('settings'), className: `w-full flex items-center space-x-3 font-medium text-sm pl-3.5 py-2.5 rounded-lg transition-all duration-150 active:scale-[0.98] ${currentTab === 'settings'
                                        ? 'bg-surface-container-high text-primary border-l-2 border-primary-container font-semibold shadow-[inset_4px_0_12px_rgba(245,158,11,0.15)]'
                                        : 'text-on-surface-variant hover:bg-surface-container-high hover:text-primary'}`, children: [_jsx(Settings, { className: `w-4 h-4 ${currentTab === 'settings' ? 'text-primary' : ''}` }), _jsx("span", { children: "Settings" })] })] }), _jsx("div", { className: "mt-7 px-1", children: _jsxs("button", { onClick: onOpenAddModal, className: "w-full flex items-center justify-center space-x-2 border border-primary-container/30 hover:border-primary-container bg-surface-container py-2.5 px-3 rounded-lg text-on-surface text-sm font-medium hover:bg-surface-container-high active:scale-[0.98] transition-all hover:shadow-amber-glow", children: [_jsx(PlusCircle, { className: "w-4 h-4 text-primary" }), _jsx("span", { children: "Add Game" })] }) })] }), _jsxs("div", { className: "pt-4 border-t border-primary-container/20 px-1 space-y-3", children: [_jsxs("div", { className: "bg-surface-container p-2.5 rounded-lg border border-primary-container/20", children: [_jsxs("div", { className: "flex items-center justify-between text-xs font-mono text-on-surface-variant mb-1.5", children: [_jsxs("div", { className: "flex items-center space-x-1.5", children: [_jsx(HardDrive, { className: "w-3.5 h-3.5 text-primary" }), _jsx("span", { children: "Memory" })] }), _jsx("span", { className: "text-primary font-semibold", children: telemetry ? `${telemetry.ramUsagePercent}%` : 'Optimal' })] }), _jsx("div", { className: "w-full h-1.5 bg-surface-container-highest rounded-full overflow-hidden", children: _jsx("div", { className: "h-full bg-gradient-to-r from-amber-600 via-primary-container to-primary rounded-full transition-all duration-500", style: { width: `${telemetry?.ramUsagePercent || 45}%` } }) })] }), _jsxs("div", { className: "flex items-center justify-between px-1 text-xs font-mono text-on-surface-variant/80", children: [_jsxs("div", { className: "flex items-center space-x-2", children: [_jsx("span", { className: "w-2 h-2 rounded-full bg-status-running animate-pulse shadow-[0_0_8px_#22c55e]" }), _jsx("span", { className: "text-on-surface font-medium", children: "Core Ready" })] }), _jsx("span", { children: "v0.1.0" })] })] })] }) }));
};
