import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from 'react';
import { Search, Plus, Minus, Square, Copy, X } from 'lucide-react';
import { launcherApi } from '../services/launcherApi';
export const TopBar = ({ searchQuery, onSearchChange, activeFilter, onFilterChange, onOpenAddModal, showFilters = true }) => {
    const [isMaximized, setIsMaximized] = useState(false);
    useEffect(() => {
        launcherApi.isMaximized().then(setIsMaximized);
        const cleanup = launcherApi.onMaximizeChanged(setIsMaximized);
        return () => cleanup();
    }, []);
    return (_jsxs("header", { className: "h-14 fixed top-0 left-60 right-0 z-20 flex items-center justify-between select-none bg-surface/95 backdrop-blur-md border-b border-primary-container/20 px-6 titlebar-drag-region", children: [_jsxs("div", { className: "flex items-center space-x-6 flex-1 mr-4 titlebar-no-drag", children: [_jsxs("div", { className: "relative w-72 sm:w-80", children: [_jsx("span", { className: "absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-on-surface-variant", children: _jsx(Search, { className: "w-4 h-4 text-on-surface-variant/70" }) }), _jsx("input", { type: "text", value: searchQuery, onChange: (e) => onSearchChange(e.target.value), placeholder: "Search your library (Ctrl + F)...", className: "w-full bg-surface-container-low border border-outline-variant/60 focus:border-primary-container focus:ring-1 focus:ring-primary-container text-on-surface placeholder:text-on-surface-variant/50 text-xs font-medium rounded-lg pl-9 pr-8 py-1.5 focus:outline-none transition-colors" }), searchQuery && (_jsx("button", { onClick: () => onSearchChange(''), className: "absolute inset-y-0 right-0 pr-2.5 flex items-center text-on-surface-variant hover:text-on-surface", children: _jsx(X, { className: "w-3.5 h-3.5" }) }))] }), showFilters && (_jsxs("nav", { className: "flex items-center space-x-5 text-xs font-semibold", children: [_jsx("button", { onClick: () => onFilterChange('all'), className: `pb-1 transition-all duration-150 ${activeFilter === 'all'
                                    ? 'text-primary border-b-2 border-primary-container'
                                    : 'text-on-surface-variant hover:text-primary border-b-2 border-transparent'}`, children: "All Games" }), _jsx("button", { onClick: () => onFilterChange('installed'), className: `pb-1 transition-all duration-150 ${activeFilter === 'installed'
                                    ? 'text-primary border-b-2 border-primary-container'
                                    : 'text-on-surface-variant hover:text-primary border-b-2 border-transparent'}`, children: "Installed" }), _jsx("button", { onClick: () => onFilterChange('favorites'), className: `pb-1 transition-all duration-150 ${activeFilter === 'favorites'
                                    ? 'text-primary border-b-2 border-primary-container'
                                    : 'text-on-surface-variant hover:text-primary border-b-2 border-transparent'}`, children: "Favorites" })] }))] }), _jsxs("div", { className: "flex items-center space-x-3 shrink-0 titlebar-no-drag", children: [_jsxs("button", { onClick: onOpenAddModal, className: "bg-primary-container hover:bg-primary text-black font-semibold text-xs px-3.5 py-1.5 rounded-lg flex items-center space-x-1.5 active:scale-[0.98] transition-all duration-150 shadow-sm shadow-primary-container/20", children: [_jsx(Plus, { className: "w-4 h-4 stroke-[2.5]" }), _jsx("span", { children: "Add Game" })] }), _jsxs("div", { className: "flex items-center space-x-1 ml-2 pl-2 border-l border-outline-variant/30", children: [_jsx("button", { onClick: () => launcherApi.minimizeWindow(), className: "p-1.5 rounded hover:bg-surface-variant text-on-surface-variant hover:text-on-surface transition-colors", title: "Minimize", children: _jsx(Minus, { className: "w-3.5 h-3.5" }) }), _jsx("button", { onClick: () => launcherApi.maximizeWindow(), className: "p-1.5 rounded hover:bg-surface-variant text-on-surface-variant hover:text-on-surface transition-colors", title: isMaximized ? 'Restore' : 'Maximize', children: isMaximized ? _jsx(Copy, { className: "w-3 h-3" }) : _jsx(Square, { className: "w-3 h-3" }) }), _jsx("button", { onClick: () => launcherApi.closeWindow(), className: "p-1.5 rounded hover:bg-status-error hover:text-white text-on-surface-variant transition-colors", title: "Close", children: _jsx(X, { className: "w-3.5 h-3.5" }) })] })] })] }));
};
